package vn.com.luanvan.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Chude generated by hbm2java
 */
@Entity
@Table(name = "chude", catalog = "tracnghiem")
public class ChuDe implements java.io.Serializable {

	private int mscd;
	private String cdTen;

	public ChuDe() {
	}

	public ChuDe(int mscd) {
		this.mscd = mscd;
	}

	public ChuDe(int mscd, String cdTen) {
		this.mscd = mscd;
		this.cdTen = cdTen;
	}

	@Id
	@Column(name = "MSCD", unique = true, nullable = false)
	public int getMscd() {
		return this.mscd;
	}

	public void setMscd(int mscd) {
		this.mscd = mscd;
	}

	@Column(name = "CD_Ten", length = 100)
	public String getCdTen() {
		return this.cdTen;
	}

	public void setCdTen(String cdTen) {
		this.cdTen = cdTen;
	}

}
