package vn.com.luanvan.model;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Dethi generated by hbm2java
 */
@Entity
@Table(name = "dethi", catalog = "tracnghiem")
public class DeThi implements java.io.Serializable {

	private Integer made;
	private String tende;
	private Short heso;
	private Integer thoigianlambai;
	private Boolean trangthai;
	private String matkhaudethi;
	private Date ngaytaode;
	private Date ngaycapnhat;
	private String dando;
	private Integer solanthi;
	private Integer mscd;

	public DeThi() {
	}

	public DeThi(String tende, Short heso, Integer thoigianlambai,
			Boolean trangthai, String matkhaudethi, Date ngaytaode,
			Date ngaycapnhat, String dando, Integer solanthi, Integer mscd) {
		this.tende = tende;
		this.heso = heso;
		this.thoigianlambai = thoigianlambai;
		this.trangthai = trangthai;
		this.matkhaudethi = matkhaudethi;
		this.ngaytaode = ngaytaode;
		this.ngaycapnhat = ngaycapnhat;
		this.dando = dando;
		this.solanthi = solanthi;
		this.mscd = mscd;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "made", unique = true, nullable = false)
	public Integer getMade() {
		return this.made;
	}

	public void setMade(Integer made) {
		this.made = made;
	}

	@Column(name = "tende", length = 100)
	public String getTende() {
		return this.tende;
	}

	public void setTende(String tende) {
		this.tende = tende;
	}

	@Column(name = "heso")
	public Short getHeso() {
		return this.heso;
	}

	public void setHeso(Short heso) {
		this.heso = heso;
	}

	@Column(name = "thoigianlambai")
	public Integer getThoigianlambai() {
		return this.thoigianlambai;
	}

	public void setThoigianlambai(Integer thoigianlambai) {
		this.thoigianlambai = thoigianlambai;
	}

	@Column(name = "trangthai")
	public Boolean getTrangthai() {
		return this.trangthai;
	}

	public void setTrangthai(Boolean trangthai) {
		this.trangthai = trangthai;
	}

	@Column(name = "matkhaudethi", length = 20)
	public String getMatkhaudethi() {
		return this.matkhaudethi;
	}

	public void setMatkhaudethi(String matkhaudethi) {
		this.matkhaudethi = matkhaudethi;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ngaytaode", length = 19)
	public Date getNgaytaode() {
		return this.ngaytaode;
	}

	public void setNgaytaode(Date ngaytaode) {
		this.ngaytaode = ngaytaode;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ngaycapnhat", length = 19)
	public Date getNgaycapnhat() {
		return this.ngaycapnhat;
	}

	public void setNgaycapnhat(Date ngaycapnhat) {
		this.ngaycapnhat = ngaycapnhat;
	}

	@Column(name = "dando", length = 65535)
	public String getDando() {
		return this.dando;
	}

	public void setDando(String dando) {
		this.dando = dando;
	}

	@Column(name = "solanthi")
	public Integer getSolanthi() {
		return this.solanthi;
	}

	public void setSolanthi(Integer solanthi) {
		this.solanthi = solanthi;
	}

	@Column(name = "mscd")
	public Integer getMscd() {
		return this.mscd;
	}

	public void setMscd(Integer mscd) {
		this.mscd = mscd;
	}

}

