// default package
// Generated Mar 21, 2015 12:26:30 PM by Hibernate Tools 4.3.1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Traloi generated by hbm2java
 */
@Entity
@Table(name = "traloi", catalog = "tracnghiem")
public class Traloi implements java.io.Serializable {

	private TraloiId id;
	private Cauhoi cauhoi;
	private User user;
	private float tlDiem;
	private String tlNoidung;

	public Traloi() {
	}

	public Traloi(TraloiId id, Cauhoi cauhoi, User user, float tlDiem,
			String tlNoidung) {
		this.id = id;
		this.cauhoi = cauhoi;
		this.user = user;
		this.tlDiem = tlDiem;
		this.tlNoidung = tlNoidung;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "msdt", column = @Column(name = "MSDT", nullable = false)),
			@AttributeOverride(name = "msch", column = @Column(name = "MSCH", nullable = false)),
			@AttributeOverride(name = "ndTaikhoan", column = @Column(name = "ND_TAIKHOAN", nullable = false, length = 100)) })
	public TraloiId getId() {
		return this.id;
	}

	public void setId(TraloiId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "MSDT", referencedColumnName = "MSDT", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "MSCH", referencedColumnName = "MSCH", nullable = false, insertable = false, updatable = false) })
	public Cauhoi getCauhoi() {
		return this.cauhoi;
	}

	public void setCauhoi(Cauhoi cauhoi) {
		this.cauhoi = cauhoi;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ND_TAIKHOAN", nullable = false, insertable = false, updatable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "TL_DIEM", nullable = false, precision = 12, scale = 0)
	public float getTlDiem() {
		return this.tlDiem;
	}

	public void setTlDiem(float tlDiem) {
		this.tlDiem = tlDiem;
	}

	@Column(name = "TL_NOIDUNG", nullable = false, length = 1000)
	public String getTlNoidung() {
		return this.tlNoidung;
	}

	public void setTlNoidung(String tlNoidung) {
		this.tlNoidung = tlNoidung;
	}

}
