package vn.com.luanvan.model;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Cauhoi generated by hbm2java
 */
@Entity
@Table(name = "cauhoi", catalog = "tracnghiem")
public class Cauhoi implements java.io.Serializable {

	private Integer msch;
	private Dangcauhoi dangcauhoi;
	private Dethi dethi;
	private Dokho dokho;
	private String chNoidungcauhoi;
	private float chDiem;
	private String chDapandung;
	private Set<Traloi> traloisForMsdt = new HashSet<Traloi>(0);
	private Set<Traloi> traloisForMsch = new HashSet<Traloi>(0);
	private Set<Cautraloi> cautralois = new HashSet<Cautraloi>(0);

	public Cauhoi() {
	}

	public Cauhoi(Dangcauhoi dangcauhoi, Dethi dethi, Dokho dokho,
			String chNoidungcauhoi, float chDiem, String chDapandung) {
		this.dangcauhoi = dangcauhoi;
		this.dethi = dethi;
		this.dokho = dokho;
		this.chNoidungcauhoi = chNoidungcauhoi;
		this.chDiem = chDiem;
		this.chDapandung = chDapandung;
	}

	public Cauhoi(Dangcauhoi dangcauhoi, Dethi dethi, Dokho dokho,
			String chNoidungcauhoi, float chDiem, String chDapandung,
			Set<Traloi> traloisForMsdt, Set<Traloi> traloisForMsch,
			Set<Cautraloi> cautralois) {
		this.dangcauhoi = dangcauhoi;
		this.dethi = dethi;
		this.dokho = dokho;
		this.chNoidungcauhoi = chNoidungcauhoi;
		this.chDiem = chDiem;
		this.chDapandung = chDapandung;
		this.traloisForMsdt = traloisForMsdt;
		this.traloisForMsch = traloisForMsch;
		this.cautralois = cautralois;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "MSCH", unique = true, nullable = false)
	public Integer getMsch() {
		return this.msch;
	}

	public void setMsch(Integer msch) {
		this.msch = msch;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MSDCH", nullable = false)
	public Dangcauhoi getDangcauhoi() {
		return this.dangcauhoi;
	}

	public void setDangcauhoi(Dangcauhoi dangcauhoi) {
		this.dangcauhoi = dangcauhoi;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MSDT", nullable = false)
	public Dethi getDethi() {
		return this.dethi;
	}

	public void setDethi(Dethi dethi) {
		this.dethi = dethi;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MSDK", nullable = false)
	public Dokho getDokho() {
		return this.dokho;
	}

	public void setDokho(Dokho dokho) {
		this.dokho = dokho;
	}

	@Column(name = "CH_NOIDUNGCAUHOI", nullable = false)
	public String getChNoidungcauhoi() {
		return this.chNoidungcauhoi;
	}

	public void setChNoidungcauhoi(String chNoidungcauhoi) {
		this.chNoidungcauhoi = chNoidungcauhoi;
	}

	@Column(name = "CH_DIEM", nullable = false, precision = 12, scale = 0)
	public float getChDiem() {
		return this.chDiem;
	}

	public void setChDiem(float chDiem) {
		this.chDiem = chDiem;
	}

	@Column(name = "CH_DAPANDUNG", nullable = true, length = 2)
	public String getChDapandung() {
		return this.chDapandung;
	}

	public void setChDapandung(String chDapandung) {
		this.chDapandung = chDapandung;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cauhoiByMsdt")
	public Set<Traloi> getTraloisForMsdt() {
		return this.traloisForMsdt;
	}

	public void setTraloisForMsdt(Set<Traloi> traloisForMsdt) {
		this.traloisForMsdt = traloisForMsdt;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cauhoiByMsch")
	public Set<Traloi> getTraloisForMsch() {
		return this.traloisForMsch;
	}

	public void setTraloisForMsch(Set<Traloi> traloisForMsch) {
		this.traloisForMsch = traloisForMsch;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cauhoi")
	public Set<Cautraloi> getCautralois() {
		return this.cautralois;
	}

	public void setCautralois(Set<Cautraloi> cautralois) {
		this.cautralois = cautralois;
	}

}
