package vn.com.luanvan.model;
// Generated Mar 30, 2015 9:02:58 AM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Cautraloi generated by hbm2java
 */
@Entity
@Table(name = "cautraloi", catalog = "tracnghiem")
public class Cautraloi implements java.io.Serializable {

	private int msctl;
	private Cauhoi cauhoi;
	private String ctlNoidung;

	public Cautraloi() {
	}

	public Cautraloi(int msctl, Cauhoi cauhoi, String ctlNoidung) {
		this.msctl = msctl;
		this.cauhoi = cauhoi;
		this.ctlNoidung = ctlNoidung;
	}

	@Id
	@Column(name = "MSCTL", unique = true, nullable = false)
	public int getMsctl() {
		return this.msctl;
	}

	public void setMsctl(int msctl) {
		this.msctl = msctl;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MSCH", nullable = false)
	public Cauhoi getCauhoi() {
		return this.cauhoi;
	}

	public void setCauhoi(Cauhoi cauhoi) {
		this.cauhoi = cauhoi;
	}

	@Column(name = "CTL_NOIDUNG", nullable = false)
	public String getCtlNoidung() {
		return this.ctlNoidung;
	}

	public void setCtlNoidung(String ctlNoidung) {
		this.ctlNoidung = ctlNoidung;
	}

}
