package vn.com.luanvan.model;

import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DethiLop generated by hbm2java
 */
@Entity
@Table(name = "dethi_lop", catalog = "tracnghiem")
public class DethiLop implements java.io.Serializable {

	private DethiLopId id;
	private Dethi dethi;
	private Lop lop;
	private Phongthi phongthi;
	private Date ngay;
	private Date giobatdau;
	private Date gioketthuc;

	public DethiLop() {
	}

	public DethiLop(DethiLopId id, Dethi dethi, Lop lop) {
		this.id = id;
		this.dethi = dethi;
		this.lop = lop;
	}

	public DethiLop(DethiLopId id, Dethi dethi, Lop lop, Phongthi phongthi,
			Date ngay, Date giobatdau, Date gioketthuc) {
		this.id = id;
		this.dethi = dethi;
		this.lop = lop;
		this.phongthi = phongthi;
		this.ngay = ngay;
		this.giobatdau = giobatdau;
		this.gioketthuc = gioketthuc;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "msl", column = @Column(name = "MSL", nullable = false, length = 10)),
			@AttributeOverride(name = "msdt", column = @Column(name = "MSDT", nullable = false)) })
	public DethiLopId getId() {
		return this.id;
	}

	public void setId(DethiLopId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MSDT", nullable = false, insertable = false, updatable = false)
	public Dethi getDethi() {
		return this.dethi;
	}

	public void setDethi(Dethi dethi) {
		this.dethi = dethi;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MSL", nullable = false, insertable = false, updatable = false)
	public Lop getLop() {
		return this.lop;
	}

	public void setLop(Lop lop) {
		this.lop = lop;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MSPT")
	public Phongthi getPhongthi() {
		return this.phongthi;
	}

	public void setPhongthi(Phongthi phongthi) {
		this.phongthi = phongthi;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "NGAY", length = 0)
	public Date getNgay() {
		return this.ngay;
	}

	public void setNgay(Date ngay) {
		this.ngay = ngay;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "GIOBATDAU", length = 0)
	public Date getGiobatdau() {
		return this.giobatdau;
	}

	public void setGiobatdau(Date giobatdau) {
		this.giobatdau = giobatdau;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "GIOKETTHUC", length = 0)
	public Date getGioketthuc() {
		return this.gioketthuc;
	}

	public void setGioketthuc(Date gioketthuc) {
		this.gioketthuc = gioketthuc;
	}

}
