package vn.com.luanvan.model;

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Phancongvaitro generated by hbm2java
 */
@Entity
@Table(name = "phancongvaitro", catalog = "tracnghiem")
public class Phancongvaitro implements java.io.Serializable {

	private Integer mspcvt;
	private Dethi dethi;
	private User user;
	private Vaitro vaitro;
	private int mscda;
	private Integer mspt;
	private Date ngay;
	private Date giobatdau;
	private Date gioketthuc;

	public Phancongvaitro() {
	}

	public Phancongvaitro(User user, Vaitro vaitro, int mscda) {
		this.user = user;
		this.vaitro = vaitro;
		this.mscda = mscda;
	}

	public Phancongvaitro(Dethi dethi, User user, Vaitro vaitro, int mscda,
			Integer mspt, Date ngay, Date giobatdau, Date gioketthuc) {
		this.dethi = dethi;
		this.user = user;
		this.vaitro = vaitro;
		this.mscda = mscda;
		this.mspt = mspt;
		this.ngay = ngay;
		this.giobatdau = giobatdau;
		this.gioketthuc = gioketthuc;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "MSPCVT", unique = true, nullable = false)
	public Integer getMspcvt() {
		return this.mspcvt;
	}

	public void setMspcvt(Integer mspcvt) {
		this.mspcvt = mspcvt;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MSDT")
	public Dethi getDethi() {
		return this.dethi;
	}

	public void setDethi(Dethi dethi) {
		this.dethi = dethi;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ND_TAIKHOAN", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MSVT", nullable = false)
	public Vaitro getVaitro() {
		return this.vaitro;
	}

	public void setVaitro(Vaitro vaitro) {
		this.vaitro = vaitro;
	}

	@Column(name = "MSCDA", nullable = false)
	public int getMscda() {
		return this.mscda;
	}

	public void setMscda(int mscda) {
		this.mscda = mscda;
	}

	@Column(name = "MSPT")
	public Integer getMspt() {
		return this.mspt;
	}

	public void setMspt(Integer mspt) {
		this.mspt = mspt;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "NGAY", length = 0)
	public Date getNgay() {
		return this.ngay;
	}

	public void setNgay(Date ngay) {
		this.ngay = ngay;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "GIOBATDAU", length = 0)
	public Date getGiobatdau() {
		return this.giobatdau;
	}

	public void setGiobatdau(Date giobatdau) {
		this.giobatdau = giobatdau;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "GIOKETTHUC", length = 0)
	public Date getGioketthuc() {
		return this.gioketthuc;
	}

	public void setGioketthuc(Date gioketthuc) {
		this.gioketthuc = gioketthuc;
	}


}
