// default package
// Generated Mar 10, 2015 9:46:01 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Hinhanh generated by hbm2java
 */
@Entity
@Table(name = "hinhanh", catalog = "thitracnghiem")
public class Hinhanh implements java.io.Serializable {

	private int msha;
	private Cauhoi cauhoi;
	private Cautraloi cautraloi;
	private String haNoidung;

	public Hinhanh() {
	}

	public Hinhanh(int msha, String haNoidung) {
		this.msha = msha;
		this.haNoidung = haNoidung;
	}

	public Hinhanh(int msha, Cauhoi cauhoi, Cautraloi cautraloi,
			String haNoidung) {
		this.msha = msha;
		this.cauhoi = cauhoi;
		this.cautraloi = cautraloi;
		this.haNoidung = haNoidung;
	}

	@Id
	@Column(name = "MSHA", unique = true, nullable = false)
	public int getMsha() {
		return this.msha;
	}

	public void setMsha(int msha) {
		this.msha = msha;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({ @JoinColumn(name = "MSDT", referencedColumnName = "MSDT"),
			@JoinColumn(name = "MSCH", referencedColumnName = "MSCH") })
	public Cauhoi getCauhoi() {
		return this.cauhoi;
	}

	public void setCauhoi(Cauhoi cauhoi) {
		this.cauhoi = cauhoi;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "MSDT", referencedColumnName = "MSDT", insertable = false, updatable = false),
			@JoinColumn(name = "MSCH", referencedColumnName = "MSCH", insertable = false, updatable = false),
			@JoinColumn(name = "MSCTL", referencedColumnName = "MSCTL", insertable = false, updatable = false) })
	public Cautraloi getCautraloi() {
		return this.cautraloi;
	}

	public void setCautraloi(Cautraloi cautraloi) {
		this.cautraloi = cautraloi;
	}

	@Column(name = "HA_NOIDUNG", nullable = false)
	public String getHaNoidung() {
		return this.haNoidung;
	}

	public void setHaNoidung(String haNoidung) {
		this.haNoidung = haNoidung;
	}

}
