// default package
// Generated Mar 10, 2015 9:46:01 PM by Hibernate Tools 4.3.1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Phancongvaitro generated by hbm2java
 */
@Entity
@Table(name = "phancongvaitro", catalog = "thitracnghiem")
public class Phancongvaitro implements java.io.Serializable {

	private PhancongvaitroId id;
	private Dethi dethi;
	private Nguoidung nguoidung;
	private Vaitro vaitro;
	private int mscd;

	public Phancongvaitro() {
	}

	public Phancongvaitro(PhancongvaitroId id, Dethi dethi,
			Nguoidung nguoidung, Vaitro vaitro, int mscd) {
		this.id = id;
		this.dethi = dethi;
		this.nguoidung = nguoidung;
		this.vaitro = vaitro;
		this.mscd = mscd;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "msdt", column = @Column(name = "MSDT", nullable = false, length = 5)),
			@AttributeOverride(name = "ndTaikhoan", column = @Column(name = "ND_TAIKHOAN", nullable = false, length = 10)),
			@AttributeOverride(name = "msvt", column = @Column(name = "MSVT", nullable = false)) })
	public PhancongvaitroId getId() {
		return this.id;
	}

	public void setId(PhancongvaitroId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MSDT", nullable = false, insertable = false, updatable = false)
	public Dethi getDethi() {
		return this.dethi;
	}

	public void setDethi(Dethi dethi) {
		this.dethi = dethi;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ND_TAIKHOAN", nullable = false, insertable = false, updatable = false)
	public Nguoidung getNguoidung() {
		return this.nguoidung;
	}

	public void setNguoidung(Nguoidung nguoidung) {
		this.nguoidung = nguoidung;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MSVT", nullable = false, insertable = false, updatable = false)
	public Vaitro getVaitro() {
		return this.vaitro;
	}

	public void setVaitro(Vaitro vaitro) {
		this.vaitro = vaitro;
	}

	@Column(name = "MSCD", nullable = false)
	public int getMscd() {
		return this.mscd;
	}

	public void setMscd(int mscd) {
		this.mscd = mscd;
	}

}
