// default package
// Generated Mar 10, 2015 9:46:01 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Thi generated by hbm2java
 */
@Entity
@Table(name = "thi", catalog = "thitracnghiem")
public class Thi implements java.io.Serializable {

	private ThiId id;
	private Dethi dethi;
	private Nguoidung nguoidung;
	private Phongthi phongthi;
	private boolean TDanhdau;
	private boolean TKhoabailam;
	private Date TNgaylam;
	private Date TThoigianbatdau;
	private Date TThoigianketthuc;
	private float TDiem;

	public Thi() {
	}

	public Thi(ThiId id, Dethi dethi, Nguoidung nguoidung, Phongthi phongthi,
			boolean TDanhdau, boolean TKhoabailam, Date TNgaylam,
			Date TThoigianbatdau, Date TThoigianketthuc, float TDiem) {
		this.id = id;
		this.dethi = dethi;
		this.nguoidung = nguoidung;
		this.phongthi = phongthi;
		this.TDanhdau = TDanhdau;
		this.TKhoabailam = TKhoabailam;
		this.TNgaylam = TNgaylam;
		this.TThoigianbatdau = TThoigianbatdau;
		this.TThoigianketthuc = TThoigianketthuc;
		this.TDiem = TDiem;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "ndTaikhoan", column = @Column(name = "ND_TAIKHOAN", nullable = false, length = 10)),
			@AttributeOverride(name = "msdt", column = @Column(name = "MSDT", nullable = false, length = 5)) })
	public ThiId getId() {
		return this.id;
	}

	public void setId(ThiId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MSDT", nullable = false, insertable = false, updatable = false)
	public Dethi getDethi() {
		return this.dethi;
	}

	public void setDethi(Dethi dethi) {
		this.dethi = dethi;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ND_TAIKHOAN", nullable = false, insertable = false, updatable = false)
	public Nguoidung getNguoidung() {
		return this.nguoidung;
	}

	public void setNguoidung(Nguoidung nguoidung) {
		this.nguoidung = nguoidung;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MSPT", nullable = false)
	public Phongthi getPhongthi() {
		return this.phongthi;
	}

	public void setPhongthi(Phongthi phongthi) {
		this.phongthi = phongthi;
	}

	@Column(name = "T_DANHDAU", nullable = false)
	public boolean isTDanhdau() {
		return this.TDanhdau;
	}

	public void setTDanhdau(boolean TDanhdau) {
		this.TDanhdau = TDanhdau;
	}

	@Column(name = "T_KHOABAILAM", nullable = false)
	public boolean isTKhoabailam() {
		return this.TKhoabailam;
	}

	public void setTKhoabailam(boolean TKhoabailam) {
		this.TKhoabailam = TKhoabailam;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "T_NGAYLAM", nullable = false, length = 0)
	public Date getTNgaylam() {
		return this.TNgaylam;
	}

	public void setTNgaylam(Date TNgaylam) {
		this.TNgaylam = TNgaylam;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "T_THOIGIANBATDAU", nullable = false, length = 0)
	public Date getTThoigianbatdau() {
		return this.TThoigianbatdau;
	}

	public void setTThoigianbatdau(Date TThoigianbatdau) {
		this.TThoigianbatdau = TThoigianbatdau;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "T_THOIGIANKETTHUC", nullable = false, length = 0)
	public Date getTThoigianketthuc() {
		return this.TThoigianketthuc;
	}

	public void setTThoigianketthuc(Date TThoigianketthuc) {
		this.TThoigianketthuc = TThoigianketthuc;
	}

	@Column(name = "T_DIEM", nullable = false, precision = 12, scale = 0)
	public float getTDiem() {
		return this.TDiem;
	}

	public void setTDiem(float TDiem) {
		this.TDiem = TDiem;
	}

}
