// default package
// Generated Mar 10, 2015 9:46:01 PM by Hibernate Tools 4.3.1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * Traloi generated by hbm2java
 */
@Entity
@Table(name = "traloi", catalog = "thitracnghiem")
public class Traloi implements java.io.Serializable {

	private TraloiId id;
	private Cauhoi cauhoi;
	private Nguoidung nguoidung;
	private String tlNoidung;
	private float tlDiem;
	private Cauhoi cauhoi;

	public Traloi() {
	}

	public Traloi(TraloiId id, Cauhoi cauhoi, Nguoidung nguoidung, float tlDiem) {
		this.id = id;
		this.cauhoi = cauhoi;
		this.nguoidung = nguoidung;
		this.tlDiem = tlDiem;
	}

	public Traloi(TraloiId id, Cauhoi cauhoi, Nguoidung nguoidung,
			String tlNoidung, float tlDiem, Cauhoi cauhoi) {
		this.id = id;
		this.cauhoi = cauhoi;
		this.nguoidung = nguoidung;
		this.tlNoidung = tlNoidung;
		this.tlDiem = tlDiem;
		this.cauhoi = cauhoi;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "msdt", column = @Column(name = "MSDT", nullable = false, length = 5)),
			@AttributeOverride(name = "msch", column = @Column(name = "MSCH", nullable = false)),
			@AttributeOverride(name = "ndTaikhoan", column = @Column(name = "ND_TAIKHOAN", nullable = false, length = 10)) })
	public TraloiId getId() {
		return this.id;
	}

	public void setId(TraloiId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "MSDT", referencedColumnName = "MSDT", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "MSCH", referencedColumnName = "MSCH", nullable = false, insertable = false, updatable = false) })
	public Cauhoi getCauhoi() {
		return this.cauhoi;
	}

	public void setCauhoi(Cauhoi cauhoi) {
		this.cauhoi = cauhoi;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ND_TAIKHOAN", nullable = false, insertable = false, updatable = false)
	public Nguoidung getNguoidung() {
		return this.nguoidung;
	}

	public void setNguoidung(Nguoidung nguoidung) {
		this.nguoidung = nguoidung;
	}

	@Column(name = "TL_NOIDUNG", length = 5)
	public String getTlNoidung() {
		return this.tlNoidung;
	}

	public void setTlNoidung(String tlNoidung) {
		this.tlNoidung = tlNoidung;
	}

	@Column(name = "TL_DIEM", nullable = false, precision = 12, scale = 0)
	public float getTlDiem() {
		return this.tlDiem;
	}

	public void setTlDiem(float tlDiem) {
		this.tlDiem = tlDiem;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "traloi")
	public Cauhoi getCauhoi() {
		return this.cauhoi;
	}

	public void setCauhoi(Cauhoi cauhoi) {
		this.cauhoi = cauhoi;
	}

}
