// default package
// Generated Apr 23, 2015 5:07:01 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Hocky generated by hbm2java
 */
@Entity
@Table(name = "hocky", catalog = "tracnghiem")
public class Hocky implements java.io.Serializable {

	private Integer mshk;
	private Set<Dethi> dethis = new HashSet<Dethi>(0);

	public Hocky() {
	}

	public Hocky(Set<Dethi> dethis) {
		this.dethis = dethis;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "MSHK", unique = true, nullable = false)
	public Integer getMshk() {
		return this.mshk;
	}

	public void setMshk(Integer mshk) {
		this.mshk = mshk;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hocky")
	public Set<Dethi> getDethis() {
		return this.dethis;
	}

	public void setDethis(Set<Dethi> dethis) {
		this.dethis = dethis;
	}

}
