// default package
// Generated Apr 23, 2015 5:07:01 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Thi generated by hbm2java
 */
@Entity
@Table(name = "thi", catalog = "tracnghiem")
public class Thi implements java.io.Serializable {

	private Integer mst;
	private Dethi dethi;
	private Phongthi phongthi;
	private User user;
	private boolean TDanhdau;
	private boolean TKhoabailam;
	private Date TNgaylam;
	private Date TThoigianbatdau;
	private Date TThoigianketthuc;
	private float TDiem;

	public Thi() {
	}

	public Thi(Dethi dethi, Phongthi phongthi, User user, boolean TDanhdau,
			boolean TKhoabailam, Date TNgaylam, Date TThoigianbatdau,
			Date TThoigianketthuc, float TDiem) {
		this.dethi = dethi;
		this.phongthi = phongthi;
		this.user = user;
		this.TDanhdau = TDanhdau;
		this.TKhoabailam = TKhoabailam;
		this.TNgaylam = TNgaylam;
		this.TThoigianbatdau = TThoigianbatdau;
		this.TThoigianketthuc = TThoigianketthuc;
		this.TDiem = TDiem;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "MST", unique = true, nullable = false)
	public Integer getMst() {
		return this.mst;
	}

	public void setMst(Integer mst) {
		this.mst = mst;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MSDT", nullable = false)
	public Dethi getDethi() {
		return this.dethi;
	}

	public void setDethi(Dethi dethi) {
		this.dethi = dethi;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MSPT", nullable = false)
	public Phongthi getPhongthi() {
		return this.phongthi;
	}

	public void setPhongthi(Phongthi phongthi) {
		this.phongthi = phongthi;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ND_TAIKHOAN", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "T_DANHDAU", nullable = false)
	public boolean isTDanhdau() {
		return this.TDanhdau;
	}

	public void setTDanhdau(boolean TDanhdau) {
		this.TDanhdau = TDanhdau;
	}

	@Column(name = "T_KHOABAILAM", nullable = false)
	public boolean isTKhoabailam() {
		return this.TKhoabailam;
	}

	public void setTKhoabailam(boolean TKhoabailam) {
		this.TKhoabailam = TKhoabailam;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "T_NGAYLAM", nullable = false, length = 0)
	public Date getTNgaylam() {
		return this.TNgaylam;
	}

	public void setTNgaylam(Date TNgaylam) {
		this.TNgaylam = TNgaylam;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "T_THOIGIANBATDAU", nullable = false, length = 0)
	public Date getTThoigianbatdau() {
		return this.TThoigianbatdau;
	}

	public void setTThoigianbatdau(Date TThoigianbatdau) {
		this.TThoigianbatdau = TThoigianbatdau;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "T_THOIGIANKETTHUC", nullable = false, length = 0)
	public Date getTThoigianketthuc() {
		return this.TThoigianketthuc;
	}

	public void setTThoigianketthuc(Date TThoigianketthuc) {
		this.TThoigianketthuc = TThoigianketthuc;
	}

	@Column(name = "T_DIEM", nullable = false, precision = 12, scale = 0)
	public float getTDiem() {
		return this.TDiem;
	}

	public void setTDiem(float TDiem) {
		this.TDiem = TDiem;
	}

}
