package vn.com.luanvan.model;
// Generated Mar 11, 2015 5:37:47 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Chude generated by hbm2java
 */
@Entity
@Table(name = "chude", catalog = "tracnghiem")
public class Chude implements java.io.Serializable {

	private int mscd;
	private String nd_taikhoan;
	private String cdTen;
	private Set<Dethi> dethis = new HashSet<Dethi>(0);

	public Chude() {
	}

	public Chude(String nd_taikhoan, int mscd, Monhoc monhoc, String cdTen) {
		this.nd_taikhoan = nd_taikhoan;
		this.mscd = mscd;
		this.cdTen = cdTen;
	}

	public Chude(String nd_taikhoan, int mscd, Monhoc monhoc, String cdTen, Set<Dethi> dethis) {
		this.mscd = mscd;
		this.cdTen = cdTen;
		this.dethis = dethis;
		this.nd_taikhoan = nd_taikhoan;
	}

	@Id
	@Column(name = "MSCD", unique = true, nullable = false)
	public int getMscd() {
		return this.mscd;
	}

	public void setMscd(int mscd) {
		this.mscd = mscd;
	}

	
	@Column(name = "ND_TAIKHOAN", nullable = false, length = 100)
	public String getNdTaikhoan() {
		return this.nd_taikhoan;
	}

	public void setNdTaikhoan(String nd_taikhoan) {
		this.nd_taikhoan = nd_taikhoan;
	}

	@Column(name = "CD_TEN", nullable = false, length = 100)
	public String getCdTen() {
		return this.cdTen;
	}

	public void setCdTen(String cdTen) {
		this.cdTen = cdTen;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "chude")
	public Set<Dethi> getDethis() {
		return this.dethis;
	}

	public void setDethis(Set<Dethi> dethis) {
		this.dethis = dethis;
	}

}
