package vn.com.luanvan.model;

import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Phancongvaitro generated by hbm2java
 */
@Entity
@Table(name = "phancongvaitro", catalog = "tracnghiem")
public class Phancongvaitro implements java.io.Serializable {

	private PhancongvaitroId id;
	private Dethi dethi;
	private Phongthi phongthi;
	private User user;
	private Vaitro vaitro;
	private Date thoigian;
	private int mscda;

	public Phancongvaitro() {
	}

	public Phancongvaitro(PhancongvaitroId id, Dethi dethi, User user,
			Vaitro vaitro, int mscda) {
		this.id = id;
		this.dethi = dethi;
		this.user = user;
		this.vaitro = vaitro;
		this.mscda = mscda;
	}

	public Phancongvaitro(PhancongvaitroId id, Dethi dethi, Phongthi phongthi,
			User user, Vaitro vaitro, Date thoigian, int mscda) {
		this.id = id;
		this.dethi = dethi;
		this.phongthi = phongthi;
		this.user = user;
		this.vaitro = vaitro;
		this.thoigian = thoigian;
		this.mscda = mscda;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "msdt", column = @Column(name = "MSDT", nullable = false)),
			@AttributeOverride(name = "ndTaikhoan", column = @Column(name = "ND_TAIKHOAN", nullable = false, length = 100)),
			@AttributeOverride(name = "msvt", column = @Column(name = "MSVT", nullable = false)) })
	public PhancongvaitroId getId() {
		return this.id;
	}

	public void setId(PhancongvaitroId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MSDT", nullable = false, insertable = false, updatable = false)
	public Dethi getDethi() {
		return this.dethi;
	}

	public void setDethi(Dethi dethi) {
		this.dethi = dethi;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MSPT")
	public Phongthi getPhongthi() {
		return this.phongthi;
	}

	public void setPhongthi(Phongthi phongthi) {
		this.phongthi = phongthi;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ND_TAIKHOAN", nullable = false, insertable = false, updatable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MSVT", nullable = false, insertable = false, updatable = false)
	public Vaitro getVaitro() {
		return this.vaitro;
	}

	public void setVaitro(Vaitro vaitro) {
		this.vaitro = vaitro;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "thoigian", length = 0)
	public Date getThoigian() {
		return this.thoigian;
	}

	public void setThoigian(Date thoigian) {
		this.thoigian = thoigian;
	}

	@Column(name = "MSCDA", nullable = false)
	public int getMscda() {
		return this.mscda;
	}

	public void setMscda(int mscda) {
		this.mscda = mscda;
	}

}
