package vn.com.luanvan.model;
// Generated Mar 11, 2015 5:37:47 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Cauhoi generated by hbm2java
 */
@Entity
@Table(name = "cauhoi", catalog = "tracnghiem")
public class Cauhoi implements java.io.Serializable {

	private CauhoiId id;
	private Dangcauhoi dangcauhoi;
	private Dethi dethi;
	private Dokho dokho;
	private String chNoidungcauhoi;
	private float chDiem;
	private String chDapandung;
	private Set<Hinhanh> hinhanhs = new HashSet<Hinhanh>(0);
	private Set<Traloi> tralois = new HashSet<Traloi>(0);
	private Set<Cautraloi> cautralois = new HashSet<Cautraloi>(0);

	public Cauhoi() {
	}

	public Cauhoi(CauhoiId id, Dangcauhoi dangcauhoi, Dethi dethi, Dokho dokho,
			String chNoidungcauhoi, float chDiem, String chDapandung) {
		this.id = id;
		this.dangcauhoi = dangcauhoi;
		this.dethi = dethi;
		this.dokho = dokho;
		this.chNoidungcauhoi = chNoidungcauhoi;
		this.chDiem = chDiem;
		this.chDapandung = chDapandung;
	}

	public Cauhoi(CauhoiId id, Dangcauhoi dangcauhoi, Dethi dethi, Dokho dokho,
			String chNoidungcauhoi, float chDiem, String chDapandung,
			Set<Hinhanh> hinhanhs, Set<Traloi> tralois,
			Set<Cautraloi> cautralois) {
		this.id = id;
		this.dangcauhoi = dangcauhoi;
		this.dethi = dethi;
		this.dokho = dokho;
		this.chNoidungcauhoi = chNoidungcauhoi;
		this.chDiem = chDiem;
		this.chDapandung = chDapandung;
		this.hinhanhs = hinhanhs;
		this.tralois = tralois;
		this.cautralois = cautralois;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "msdt", column = @Column(name = "MSDT", nullable = false, length = 5)),
			@AttributeOverride(name = "msch", column = @Column(name = "MSCH", nullable = false)) })
	public CauhoiId getId() {
		return this.id;
	}

	public void setId(CauhoiId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MSDCH", nullable = false)
	public Dangcauhoi getDangcauhoi() {
		return this.dangcauhoi;
	}

	public void setDangcauhoi(Dangcauhoi dangcauhoi) {
		this.dangcauhoi = dangcauhoi;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MSDT", nullable = false, insertable = false, updatable = false)
	public Dethi getDethi() {
		return this.dethi;
	}

	public void setDethi(Dethi dethi) {
		this.dethi = dethi;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MSDK", nullable = false)
	public Dokho getDokho() {
		return this.dokho;
	}

	public void setDokho(Dokho dokho) {
		this.dokho = dokho;
	}

	@Column(name = "CH_NOIDUNGCAUHOI", nullable = false, length = 1000)
	public String getChNoidungcauhoi() {
		return this.chNoidungcauhoi;
	}

	public void setChNoidungcauhoi(String chNoidungcauhoi) {
		this.chNoidungcauhoi = chNoidungcauhoi;
	}

	@Column(name = "CH_DIEM", nullable = false, precision = 12, scale = 0)
	public float getChDiem() {
		return this.chDiem;
	}

	public void setChDiem(float chDiem) {
		this.chDiem = chDiem;
	}

	@Column(name = "CH_DAPANDUNG", nullable = false, length = 2)
	public String getChDapandung() {
		return this.chDapandung;
	}

	public void setChDapandung(String chDapandung) {
		this.chDapandung = chDapandung;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cauhoi")
	public Set<Hinhanh> getHinhanhs() {
		return this.hinhanhs;
	}

	public void setHinhanhs(Set<Hinhanh> hinhanhs) {
		this.hinhanhs = hinhanhs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cauhoi")
	public Set<Traloi> getTralois() {
		return this.tralois;
	}

	public void setTralois(Set<Traloi> tralois) {
		this.tralois = tralois;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cauhoi")
	public Set<Cautraloi> getCautralois() {
		return this.cautralois;
	}

	public void setCautralois(Set<Cautraloi> cautralois) {
		this.cautralois = cautralois;
	}

}
