package vn.com.luanvan.model;
// Generated Mar 11, 2015 5:37:47 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Nienkhoa generated by hbm2java
 */
@Entity
@Table(name = "nienkhoa", catalog = "tracnghiem")
public class Nienkhoa implements java.io.Serializable {

	private int msnk;
	private String nkTen;
	private int nkNambatdau;
	private int nkNamketthuc;
	private int nkNgaybatdau;
	private int nkNgayketthuc;
	private Set<Dethi> dethis = new HashSet<Dethi>(0);

	public Nienkhoa() {
	}

	public Nienkhoa(int msnk, String nkTen, int nkNambatdau, int nkNamketthuc,
			int nkNgaybatdau, int nkNgayketthuc) {
		this.msnk = msnk;
		this.nkTen = nkTen;
		this.nkNambatdau = nkNambatdau;
		this.nkNamketthuc = nkNamketthuc;
		this.nkNgaybatdau = nkNgaybatdau;
		this.nkNgayketthuc = nkNgayketthuc;
	}

	public Nienkhoa(int msnk, String nkTen, int nkNambatdau, int nkNamketthuc,
			int nkNgaybatdau, int nkNgayketthuc, Set<Dethi> dethis) {
		this.msnk = msnk;
		this.nkTen = nkTen;
		this.nkNambatdau = nkNambatdau;
		this.nkNamketthuc = nkNamketthuc;
		this.nkNgaybatdau = nkNgaybatdau;
		this.nkNgayketthuc = nkNgayketthuc;
		this.dethis = dethis;
	}

	@Id
	@Column(name = "MSNK", unique = true, nullable = false)
	public int getMsnk() {
		return this.msnk;
	}

	public void setMsnk(int msnk) {
		this.msnk = msnk;
	}

	@Column(name = "NK_TEN", nullable = false, length = 20)
	public String getNkTen() {
		return this.nkTen;
	}

	public void setNkTen(String nkTen) {
		this.nkTen = nkTen;
	}

	@Column(name = "NK_NAMBATDAU", nullable = false)
	public int getNkNambatdau() {
		return this.nkNambatdau;
	}

	public void setNkNambatdau(int nkNambatdau) {
		this.nkNambatdau = nkNambatdau;
	}

	@Column(name = "NK_NAMKETTHUC", nullable = false)
	public int getNkNamketthuc() {
		return this.nkNamketthuc;
	}

	public void setNkNamketthuc(int nkNamketthuc) {
		this.nkNamketthuc = nkNamketthuc;
	}

	@Column(name = "NK_NGAYBATDAU", nullable = false)
	public int getNkNgaybatdau() {
		return this.nkNgaybatdau;
	}

	public void setNkNgaybatdau(int nkNgaybatdau) {
		this.nkNgaybatdau = nkNgaybatdau;
	}

	@Column(name = "NK_NGAYKETTHUC", nullable = false)
	public int getNkNgayketthuc() {
		return this.nkNgayketthuc;
	}

	public void setNkNgayketthuc(int nkNgayketthuc) {
		this.nkNgayketthuc = nkNgayketthuc;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "nienkhoa")
	public Set<Dethi> getDethis() {
		return this.dethis;
	}

	public void setDethis(Set<Dethi> dethis) {
		this.dethis = dethis;
	}

}
