// default package
// Generated May 1, 2015 6:32:30 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Dangthi generated by hbm2java
 */
@Entity
@Table(name = "dangthi", catalog = "tracnghiem")
public class Dangthi implements java.io.Serializable {

	private Integer msdangthi;
	private String dtTen;
	private int dtHeso;
	private Set<Dethi> dethis = new HashSet<Dethi>(0);

	public Dangthi() {
	}

	public Dangthi(String dtTen, int dtHeso) {
		this.dtTen = dtTen;
		this.dtHeso = dtHeso;
	}

	public Dangthi(String dtTen, int dtHeso, Set<Dethi> dethis) {
		this.dtTen = dtTen;
		this.dtHeso = dtHeso;
		this.dethis = dethis;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "MSDANGTHI", unique = true, nullable = false)
	public Integer getMsdangthi() {
		return this.msdangthi;
	}

	public void setMsdangthi(Integer msdangthi) {
		this.msdangthi = msdangthi;
	}

	@Column(name = "DT_TEN", nullable = false, length = 100)
	public String getDtTen() {
		return this.dtTen;
	}

	public void setDtTen(String dtTen) {
		this.dtTen = dtTen;
	}

	@Column(name = "DT_HESO", nullable = false)
	public int getDtHeso() {
		return this.dtHeso;
	}

	public void setDtHeso(int dtHeso) {
		this.dtHeso = dtHeso;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dangthi")
	public Set<Dethi> getDethis() {
		return this.dethis;
	}

	public void setDethis(Set<Dethi> dethis) {
		this.dethis = dethis;
	}

}
