// default package
// Generated May 1, 2015 6:32:30 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Kithi generated by hbm2java
 */
@Entity
@Table(name = "kithi", catalog = "tracnghiem")
public class Kithi implements java.io.Serializable {

	private Integer mskt;
	private Dethi dethi;
	private String ktTen;

	public Kithi() {
	}

	public Kithi(Dethi dethi, String ktTen) {
		this.dethi = dethi;
		this.ktTen = ktTen;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "MSKT", unique = true, nullable = false)
	public Integer getMskt() {
		return this.mskt;
	}

	public void setMskt(Integer mskt) {
		this.mskt = mskt;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MSDT", nullable = false)
	public Dethi getDethi() {
		return this.dethi;
	}

	public void setDethi(Dethi dethi) {
		this.dethi = dethi;
	}

	@Column(name = "KT_TEN", nullable = false, length = 20)
	public String getKtTen() {
		return this.ktTen;
	}

	public void setKtTen(String ktTen) {
		this.ktTen = ktTen;
	}

}
