// default package
// Generated Apr 30, 2015 3:35:47 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Monhoc generated by hbm2java
 */
@Entity
@Table(name = "monhoc", catalog = "tracnghiem")
public class Monhoc implements java.io.Serializable {

	private Integer msmh;
	private String mhTen;
	private Set<Dethi> dethis = new HashSet<Dethi>(0);

	public Monhoc() {
	}

	public Monhoc(String mhTen) {
		this.mhTen = mhTen;
	}

	public Monhoc(String mhTen, Set<Dethi> dethis) {
		this.mhTen = mhTen;
		this.dethis = dethis;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "MSMH", unique = true, nullable = false)
	public Integer getMsmh() {
		return this.msmh;
	}

	public void setMsmh(Integer msmh) {
		this.msmh = msmh;
	}

	@Column(name = "MH_TEN", nullable = false, length = 100)
	public String getMhTen() {
		return this.mhTen;
	}

	public void setMhTen(String mhTen) {
		this.mhTen = mhTen;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "monhoc")
	public Set<Dethi> getDethis() {
		return this.dethis;
	}

	public void setDethis(Set<Dethi> dethis) {
		this.dethis = dethis;
	}

}
