// default package
// Generated Apr 30, 2015 3:35:47 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Nienkhoa generated by hbm2java
 */
@Entity
@Table(name = "nienkhoa", catalog = "tracnghiem")
public class Nienkhoa implements java.io.Serializable {

	private Integer msnk;
	private String nkTen;
	private int nkNambatdau;
	private int nkNamketthuc;
	private Date nkNgaybatdau;
	private Date nkNgayketthuc;
	private Set<Dethi> dethis = new HashSet<Dethi>(0);

	public Nienkhoa() {
	}

	public Nienkhoa(String nkTen, int nkNambatdau, int nkNamketthuc,
			Date nkNgaybatdau, Date nkNgayketthuc) {
		this.nkTen = nkTen;
		this.nkNambatdau = nkNambatdau;
		this.nkNamketthuc = nkNamketthuc;
		this.nkNgaybatdau = nkNgaybatdau;
		this.nkNgayketthuc = nkNgayketthuc;
	}

	public Nienkhoa(String nkTen, int nkNambatdau, int nkNamketthuc,
			Date nkNgaybatdau, Date nkNgayketthuc, Set<Dethi> dethis) {
		this.nkTen = nkTen;
		this.nkNambatdau = nkNambatdau;
		this.nkNamketthuc = nkNamketthuc;
		this.nkNgaybatdau = nkNgaybatdau;
		this.nkNgayketthuc = nkNgayketthuc;
		this.dethis = dethis;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "MSNK", unique = true, nullable = false)
	public Integer getMsnk() {
		return this.msnk;
	}

	public void setMsnk(Integer msnk) {
		this.msnk = msnk;
	}

	@Column(name = "NK_TEN", nullable = false, length = 20)
	public String getNkTen() {
		return this.nkTen;
	}

	public void setNkTen(String nkTen) {
		this.nkTen = nkTen;
	}

	@Column(name = "NK_NAMBATDAU", nullable = false)
	public int getNkNambatdau() {
		return this.nkNambatdau;
	}

	public void setNkNambatdau(int nkNambatdau) {
		this.nkNambatdau = nkNambatdau;
	}

	@Column(name = "NK_NAMKETTHUC", nullable = false)
	public int getNkNamketthuc() {
		return this.nkNamketthuc;
	}

	public void setNkNamketthuc(int nkNamketthuc) {
		this.nkNamketthuc = nkNamketthuc;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "NK_NGAYBATDAU", nullable = false, length = 0)
	public Date getNkNgaybatdau() {
		return this.nkNgaybatdau;
	}

	public void setNkNgaybatdau(Date nkNgaybatdau) {
		this.nkNgaybatdau = nkNgaybatdau;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "NK_NGAYKETTHUC", nullable = false, length = 0)
	public Date getNkNgayketthuc() {
		return this.nkNgayketthuc;
	}

	public void setNkNgayketthuc(Date nkNgayketthuc) {
		this.nkNgayketthuc = nkNgayketthuc;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "nienkhoa")
	public Set<Dethi> getDethis() {
		return this.dethis;
	}

	public void setDethis(Set<Dethi> dethis) {
		this.dethis = dethis;
	}

}
