// default package
// Generated May 1, 2015 6:32:30 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Phongthi generated by hbm2java
 */
@Entity
@Table(name = "phongthi", catalog = "tracnghiem")
public class Phongthi implements java.io.Serializable {

	private Integer mspt;
	private String ptTen;
	private Set<DethiLop> dethiLops = new HashSet<DethiLop>(0);
	private Set<Phancongvaitro> phancongvaitros = new HashSet<Phancongvaitro>(0);

	public Phongthi() {
	}

	public Phongthi(String ptTen) {
		this.ptTen = ptTen;
	}

	public Phongthi(String ptTen, Set<DethiLop> dethiLops,
			Set<Phancongvaitro> phancongvaitros) {
		this.ptTen = ptTen;
		this.dethiLops = dethiLops;
		this.phancongvaitros = phancongvaitros;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "MSPT", unique = true, nullable = false)
	public Integer getMspt() {
		return this.mspt;
	}

	public void setMspt(Integer mspt) {
		this.mspt = mspt;
	}

	@Column(name = "PT_TEN", nullable = false, length = 100)
	public String getPtTen() {
		return this.ptTen;
	}

	public void setPtTen(String ptTen) {
		this.ptTen = ptTen;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "phongthi")
	public Set<DethiLop> getDethiLops() {
		return this.dethiLops;
	}

	public void setDethiLops(Set<DethiLop> dethiLops) {
		this.dethiLops = dethiLops;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "phongthi")
	public Set<Phancongvaitro> getPhancongvaitros() {
		return this.phancongvaitros;
	}

	public void setPhancongvaitros(Set<Phancongvaitro> phancongvaitros) {
		this.phancongvaitros = phancongvaitros;
	}

}
