// default package
// Generated May 1, 2015 6:32:30 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Znguyenvikhang1101 generated by hbm2java
 */
@Entity
@Table(name = "znguyenvikhang_110_1", catalog = "tracnghiem")
public class Znguyenvikhang1101 implements java.io.Serializable {

	private int msch;
	private String dapandachon;
	private String dapandung;
	private Float diem;

	public Znguyenvikhang1101() {
	}

	public Znguyenvikhang1101(int msch) {
		this.msch = msch;
	}

	public Znguyenvikhang1101(int msch, String dapandachon, String dapandung,
			Float diem) {
		this.msch = msch;
		this.dapandachon = dapandachon;
		this.dapandung = dapandung;
		this.diem = diem;
	}

	@Id
	@Column(name = "MSCH", unique = true, nullable = false)
	public int getMsch() {
		return this.msch;
	}

	public void setMsch(int msch) {
		this.msch = msch;
	}

	@Column(name = "DAPANDACHON", length = 65535)
	public String getDapandachon() {
		return this.dapandachon;
	}

	public void setDapandachon(String dapandachon) {
		this.dapandachon = dapandachon;
	}

	@Column(name = "DAPANDUNG", length = 65535)
	public String getDapandung() {
		return this.dapandung;
	}

	public void setDapandung(String dapandung) {
		this.dapandung = dapandung;
	}

	@Column(name = "DIEM", precision = 12, scale = 0)
	public Float getDiem() {
		return this.diem;
	}

	public void setDiem(Float diem) {
		this.diem = diem;
	}

}
